server {
    listen 8080;
    root /usr/share/nginx/html;
    server_tokens off;

    location / {
        try_files $uri $uri/ =404;
    }

    location /_next/static/ {
        add_header Cache-Control "public, max-age=31536000, immutable";
    }

    error_page 404 /404.html;
}
